---
metadata:
  acronym: XAIP
  title_text: 'The Landscape of XAIP'
  citation_text: "@inproceedings{chakraborti2020emerging,\n title={The Emerging Landscape of Explainable Automated Planning {\\&}\n\t Decision Making}, \n author={Chakraborti, Tathagata and Sreedharan, Sarath and Kambhampati, Subbarao}, \n booktitle = {Proceedings of the Twenty-Ninth International Joint Conference on \n\t Artificial Intelligence, {IJCAI} 2020}, \n pages     = {4803--4811}, \n publisher = {ijcai.org}, \n year={2020}}"
  link_to_code: https://github.com/sarathsreedharan/survey-visualizer
  primary_link: https://arxiv.org/abs/2002.11697
  secondary_links: 
    - name: http://xaip.mybluemix.net/#/
  community_link: null
  info_tile: true
  info_text: Learn more about the
  info_link:
  - link: https://xaip.mybluemix.net/
    text: [XAIP workshop series]
default_view: Taxonomy
min_year: 2000
views:
- name: Taxonomy
  disabled: false
  default_tab: XAIP
  tabs:
  - tab_name: XAIP
    title_text: Various works in XAIP
    root_text: Design Element
    disabled: false
    fancy_chart: false
    input_file:
      filename: "./src/compiler/data/XAIP.xlsx"
      active_worksheet: Classification
    papers_list:
      shuffle_list: true
      key_map:
        title: 3
        abstract:
        authors: 2
        venue: 1
        sessions:
        year: 0
        keywords:
      rows:
        start: 4
        stop: 79
        exclude:
        - 79
    taxonomy:
      rows:
        start: 1
        stop: 4
        exclude:
        - 4
      columns:
        start: 5
        stop: 31
- name: Affinity
  disabled: true
- name: Network
  files_directory: "./src/compiler/pdfs"
  match_threshold: 0.25
  disabled: true
